/**
 * WordPress dependencies
 */
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

/**
 * External dependencies
 */
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const path = require('path');

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		'admin/admin': path.resolve(
			process.cwd(),
			'src/admin',
			'index.js'
		),
	},

	plugins: [
		// Include WP's plugin config.
		...defaultConfig.plugins,

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin({
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		}),
	],
};